BT_preorder_traversal.o: BT_preorder_traversal.cpp
	g++ -std=c++11 $^ -o $@

BT_inorder_traversal.o: BT_inorder_traversal.cpp
	g++ -std=c++11 $^ -o $@

BT_postorder_traversal.o: BT_postorder_traversal.cpp
	g++ -std=c++11 $^ -o $@

clean: *.o
	rm $^

.PHONY: clean
