valid_parentheses.o: valid_parentheses.cpp
	g++ -std=c++11 $^ -o $@
	
longest_valid_parentheses.o: longest_valid_parentheses.cpp
	g++ -std=c++11 $^ -o $@

reverse_polish_notation.o: reverse_polish_notation.cpp
	g++ -std=c++11 $^ -o $@
	
clean: *.o
	rm $^

.PHONY: clean
