remove_duplicate_sorted.o: remove_duplicate_sorted.cpp
	g++ -std=c++11 $^ -o $@

remove_duplicate_sorted_2.o: remove_duplicate_sorted_2.cpp
	g++ -std=c++11 $^ -o $@

search_in_rotated_sorted_array.o: search_in_rotated_sorted_array.cpp
	g++ -std=c++11 $^ -o $@

kthbiggest_sorted_arrays.o: kthbiggest_sorted_arrays.cpp
	g++ -std=c++11 $^ -o $@

longest_consecutive_sequence.o: longest_consecutive_sequence.cpp
	g++ -std=c++11 $^ -o $@

two_sum.o: two_sum.cpp
	g++ -std=c++11 $^ -o $@

remove_element.o: remove_element.cpp
	g++ -std=c++11 $^ -o $@

next_permutation.o: next_permutation.cpp
	g++ -std=c++11 $^ -o $@

permutation_sequence.o: permutation_sequence.cpp
	g++ -std=c++11 $^ -o $@

trap_rainwater.o: trap_rainwater.cpp
	g++ -std=c++11 $^ -o $@

rotate_matrix.o: rotate_matrix.cpp
	g++ -std=c++11 $^ -o $@

plus_one.o: plus_one.cpp
	g++ -std=c++11 $^ -o $@

climb_stairs.o: climb_stairs.cpp
	g++ -std=c++11 $^ -o $@

set_matrix_zero.o: set_matrix_zero.cpp
	g++ -std=c++11 $^ -o $@

gas_station.o: gas_station.cpp
	g++ -std=c++11 $^ -o $@

candy.o: candy.cpp
	g++ -std=c++11 $^ -o $@

single_number.o: single_number.cpp
	g++ -std=c++11 $^ -o $@

single_number_2.o: single_number_2.cpp
	g++ -std=c++11 $^ -o $@
	
clean: *.o
	rm $^

.PHONY: clean
